### ISSUE TITLE
Unable to feed a msg property with "dot notations" to the node 

### ISSUE THREAD

**Issue by SamuelToh** [s1r-J/node-red-contrib-loop-processing#12]
I have a property named "a.b.c" in my `msg` object.

In the javascript world we can typically access it by doing this `msg["a.b.c"]`. However the `node`'s UI is not allowing me to do so.

Not a show stopper but will be nie if we can handle such cases.

![image](https://user-images.githubusercontent.com/8707446/72588744-fc334800-3944-11ea-9492-8e53ba48f969.png)

**Comment by s1r-J** [comment]
Sorry, not only nodes in this module, but also other nodes of Node-RED does not allow to do what you say. Please make sure to `msg.`, not `msg`.
There is a workaround for this, use function node before array-loop node to move the value in  `a.b.c` property to other property.

I might add JSONata expression for problems like this.

Sincerely.
