### ISSUE TITLE
Comparators missing

### ISSUE THREAD

**Issue by pagaille** [s1r-J/node-red-contrib-loop-processing#13]
https://github.com/s1r-J/node-red-contrib-loop-processing/blob/c8908f6c9a4b9a36b49e9ddac67d5248c392c0aa/counter-loop.html#L39

Only the comparator "smaller than" is foreseen. Is this by design ? Can I simply add other cases like >, >=, <=, == in other Options ? (new to html5 sorry)

**Comment by s1r-J** [comment]
I just realized that I added other operators in my local repo owing to this issue.
I will update this module.
Thanks for pointing out.
