### ISSUE TITLE
RFE and Docup - needs a way to break out of loop

### ISSUE THREAD

**Issue by juggledad** [s1r-J/node-red-contrib-loop-processing#15]
It would be nice to show in the documentation how one could break out of the loop and/or cancel a loop with an incoming message. 

also in the 'Usage' section you have a spelling error 

Usage
Example flow is in examples/exmple.json.  <===== missing 'a' in exmple.json
Drag & drop in your Node-RED editor.

**Comment by pagaille** [comment]
I guess the OP - and me - would like to have a way to programmatically break out the while loop (before the condition is met).

**Comment by juggledad** [comment]
I should have said that there shoud be a programatic way to break out of a loop. (this is the RFE part)

 Lets say I set the node to loop 1000 times (for whatever reason) and a new event comes into the flow and I need to get out of the loop. It would be nice if I could send a msg with a msg.break or msg.reset or msg.payload set to 'break' that would stop/break out of the loop similar how you can in a switch statement, for or while loop
