### ISSUE TITLE
example flows for copy-and-paste to node-red?

### ISSUE THREAD

**Issue by ozett** [s1r-J/node-red-contrib-loop-processing#16]
yould you provide your example flows not only as an image,
but also as source-text to import into node-red?

would be helpful for a first start and  first experiments with your function node.
or do i miss it somewhere?

great thanx.

**Comment by s1r-J** [comment]
Sorry for making you wait.

This repo has example flow in `example/example.json`.
Node-RED provides seviral ways to import flow. Please refer to [here](https://nodered.org/docs/user-guide/editor/workspace/import-export).
